### PR TITLE
Updated deprecated actions

### PR DESCRIPTION
**Pull request by carceneaux**
Fixes issue #12.

Updated a single line of code in the action that was deprecated and causing GitHub Action to fail.

### CODE REVIEW

**Review by alerque — APPROVED** [review]

**Review by alerque — APPROVED** [review]
Yes, from experience I believe this is the correct way to update the deprecated feature to their new system.

**Comment by carceneaux** [comment]
Is there any reason this can't be merged?

**Comment by alerque** [comment]
Not that I can think of other than that current maintainers must not be available or paying attention right now. This is something that happens in the FOSS world ;-)

On the same topic, I'd be happy to help out as an extra maintainer of this and other projects in this org. I don't know who is in charge of administration, but at least three of the current org members know who I am from other projects around the Pandoc / Lua / GitHub world and may vouch for me.

**Comment by tarleb** [comment]
Thanks for the offer @alerque! I think we'd all be glad to distribute the weight on more shoulders. This is currently maintained by @maxheld83, with me helping out now and then. Permissions can be granted by @jgm.

**Comment by jgm** [comment]
@alerque I'm granting you access, thank you.
If there are other repos in this org you want to help with, let me know.

**Comment by alerque** [comment]
Thanks @jgm. I have some expertise and interest in the [lua-filters](https://github.com/pandoc/lua-filters) and [dockerfiles](https://github.com/pandoc/dockerfiles) repos as well. I don't know home much bandwidth I'll have for contributions but am happy to be around as a spare hand (and a light touch).

**Comment by jgm** [comment]
I'll add you to those as well.

**Comment by AlexHedley** [comment]
Could the README be updated to reflect the changes too?

**Comment by alerque** [comment]
@AlexHedley Thanks for the catch. PRs are always welcome and save time, but I just fixed this one so maybe next time.

**Pull request merged**
